symfony2/mylangs/src/Jakub/MylangsBundle/Entity/Login.php
<?php

namespace Jakub\MylangsBundle\Entity;

class Login {

    protected $_sUserName;
    protected $_sPassword;
    protected $_sLang;

    public function getPassword() {
        return ($this->_sPassword);
    }

    public function setPassword($p_sPassword) {
        $this->_sPassword = trim((string) ($p_sPassword));
    }

    public function getLang() {
        return ($this->_sLang);
    }

    public function setLang($p_sLang) {
        $this->_sLang = trim((string) ($p_sLang));
    }

    public function getUserName() {
        return ($this->_sUserName);
    }

    public function setUserName($p_sUserName) {
        $this->_sUserName = trim((string) ($p_sUserName));
    }

    public function isPasswordLegal() {
        return ($this->_sUserName != $this->_sPassword);
    }
}

symfony2/mylangs/src/Jakub/MylangsBundle/Controller/HomeController.php
<?php
namespace Jakub\MylangsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use Jakub\MylangsBundle\Entity\Login;
use Jakub\MylangsBundle\Form\Type\LoginType;

#use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
#use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class HomeController extends Controller {

    public function indexAction(Request $oRequest) {
        return ($this->forward('JakubMylangsBundle:Security:login', array($oRequest)));
    }
}

symfony2/mylangs/src/Jakub/MylangsBundle/Resources/views/Home/home.html.twig
{% extends "JakubMylangsBundle::base.html.twig" %}

{% block stylesheets %}
    <link href="{{ asset('/bundles/jakubmylangs/css/home.css') }}" type="text/css" rel="stylesheet" />
    {{ parent() }}
{% endblock %}

{% block javascripts %}
    <script language="javascript" type="text/javascript">
        $('.flag').click(
            function()
            {
                $('#{{ form.lang.vars.id}}').val($(this).attr('id'));
                
                $('.flag').each(function() {
                    $(this).removeClass('active');
                });
                
                $(this).addClass('active');
            }
        );

        // default language is en
        if (!$('#{{ form.lang.vars.id}}').val())
        {
            $('#en').click();
        }
        else // is selected
        {
            $('#' + $('#{{ form.lang.vars.id}}').val()).click();
        }
    </script>
{% endblock %}

{% block content %}
    <div class="ctn ce">
        <h1>Welcome into MyLangs application by Jakub Luczynski</h1>
        <div id="en" class="en flag"></div>
        <div id="de" class="de flag"></div>
    </div>
    <div class="ctn ce">
        <p>Please login into your account</p>
        {% if error %}
            <p>{{ error.message }}</p>
        {% endif %}
        {{ form(form, {'attr': {'novalidate': 'novalidate'}}) }}
    </div>
    <div class="ctn ce">
        <a href="{{ path('register') }}">registration</a>
    </div>
{% endblock %}

symfony2/mylangs/src/Jakub/MylangsBundle/Resources/views/Home/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html"; charset=utf-8" />
        <title>{% block title %}Hello in Mylangs application{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <link rel="shortcut icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body>
		<div>
	        <div class="en"></div>
			<div class="de"></div>
		</div>
		<div>
			<input type="text" id="login" name="login" value=""/>
			<input type="text" id="pass" name="pass" value=""/>
			<input type="submit" id="lgb" value="Login"/>
		</div>
        {% block javascripts %}{% endblock %}
    </body>
</html>